services:
  - type: web
    name: cplp-raras-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./database/gard_dev.db
      - key: PORT
        sync: false
    healthCheckPath: /health
